### ISSUE TITLE
Is lisk-elements being used?

### ISSUE THREAD

**Issue by clarkkozak** [Korben3/Decentralized-Organization-Chain#1]
Hello! This may be an inappropriate issue yet I'm learning more about Lisk any time I have a chance. I'm very inspired by this project.

Why is lisk-elements installed? I see it in the package.json. Perhaps I'm not searching the repo right yet I don't see it being used. Is that the case?

**Comment by Korben3** [comment]
Hi there!

Yes, lisk-elements is used in the client to connect and communicate to the blockchain build with the Lisk SDK.

It installs several packages, most importantly the ones starting with "@liskhq":

- bignum
- lisk-api-client
- lisk-constants
- lisk-cryptography
- lisk-passphrase
- lisk-transactions

They are used throughout the client for example to get transactions or accounts: 
https://github.com/Korben3/Decentralized-Organization-Chain/blob/master/client/src/utils/tools.js

And to create transactions, like in:
https://github.com/Korben3/Decentralized-Organization-Chain/blob/master/client/src/components/CreatePoll.js

**Comment by Korben3** [comment]
More info in the docs: https://lisk.io/documentation/lisk-sdk/reference/lisk-elements/index.html

**Comment by clarkkozak** [comment]
@Korben3 Thank you for the explanation!!!
